CREATE TABLE IF NOT EXISTS SUPERHERO (
    SUPERHERO_ID serial PRIMARY KEY,
    SUPERHERO_NAME varchar(50),
    SUPERHERO_ALIAS varchar(50),
    SUPERHERO_ORIGIN varchar(50)
    );

SELECT * FROM SUPERHERO;

CREATE TABLE IF NOT EXISTS SUPERPOWER (
    SUPERPOWER_ID serial PRIMARY KEY,
    SUPERPOWER_NAME varchar(50),
    SUPERPOWER_DESCRIPTION varchar(255)
    );
SELECT * FROM SUPERPOWER;

CREATE TABLE IF NOT EXISTS ASSISTANT (
    ASSISTANT_ID serial PRIMARY KEY,
    SUPERHERO_ID int REFERENCES SUPERHERO(SUPERHERO_ID),
    ASSISTANT_NAME varchar(50)
    );

SELECT * FROM ASSISTANT;




