INSERT INTO SUPERHERO (SUPERHERO_NAME, SUPERHERO_ALIAS, SUPERHERO_ORIGIN) VALUES ('Batman', 'Bruce Wayne', 'Arkham');
INSERT INTO SUPERHERO (SUPERHERO_NAME, SUPERHERO_ALIAS, SUPERHERO_ORIGIN) VALUES ('Wonder Woman', 'Diana Prince', 'Golden');
INSERT INTO SUPERHERO (SUPERHERO_NAME, SUPERHERO_ALIAS, SUPERHERO_ORIGIN) VALUES ('Spiderman', 'Peter Parker', 'U.S. A');
